# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ponxu
tagline:          'A Jekyll theme'
description:      '胖徐的笔记'
url:              http://ponxu.com

author:
  name:           'ponxu'
  url:            http://ponxu.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
