# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            胖徐的笔记
tagline:          'A Jekyll theme'
description:      '爱生活, 爱学习, 爱技术, 爱Java, 爱Python...爱宝马!'
url:              http://ponxu.com

author:
  name:           'ponxu'
  url:            http://ponxu.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
